-- ⚠️ NUCLEAR OPTION: This script wipes and recreates the entire database structure.
-- Run this in the Supabase SQL Editor to reset the application.

-- 1. DROP OLD TABLES (The Nuclear Option)
-- We use CASCADE to remove linked data (tracks linked to artists) automatically
DROP TABLE IF EXISTS tracks CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 2. RECREATE ARTISTS TABLE (The Parent)
create table artists (
  id bigint generated by default as identity primary key,
  name text unique not null,
  genre text,
  listeners bigint,
  image_url text,
  first_release_year integer, -- The new "Time Travel" column
  
  -- Vibe Scores (Tags)
  valence real,
  tag_energy real,

  -- Composite Audio Scores (Calculated Averages from Tracks)
  avg_bpm real default 0,
  avg_brightness real default 0,
  avg_noisiness real default 0,
  avg_warmth real default 0,
  avg_complexity real default 0,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RECREATE TRACKS TABLE (The Children)
create table tracks (
  id bigint generated by default as identity primary key,
  artist_id bigint references artists(id) on delete cascade,
  title text,
  preview_url text,
  
  -- Librosa Physics (Raw Data)
  bpm real,
  brightness real,
  noisiness real,
  warmth real,
  complexity real,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. RECREATE PROFILES TABLE (User Auth Link)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  preferences jsonb, 
  favorite_artists jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);